# Generated by Django 4.2 on 2023-08-23 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('catalog_app', '0001_initial'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('count', models.IntegerField(verbose_name='count product')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='amount')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='order_app.order', verbose_name='order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seller', verbose_name='seller')),
            ],
            options={
                'verbose_name': 'OrderItem',
            },
        ),
    ]
