# Generated by Django 4.2 on 2023-08-23 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='sum',
            new_name='amount',
        ),
    ]
