# Generated by Django 4.2 on 2023-09-21 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('EXPRESS', 'express delivery'), ('REGULAR', 'reqular delivery')], default='REGULAR', max_length=10, verbose_name='delivery type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(choices=[('bank_card', 'bank card'), ('spb', 'spb')], default='bank_card', max_length=10, verbose_name='payment type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NOT_PAID', 'is not paid'), ('PAID', 'is paid'), ('DELIVERY', 'is delivered'), ('CLOSE', 'is closed')], default='NOT_PAID', max_length=10, verbose_name='status'),
        ),
    ]
