# Generated by Django 4.2 on 2023-08-24 14:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_rename_sum_order_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.0'), max_digits=10, verbose_name='order amount'),
        ),
    ]
