# Generated by Django 4.2 on 2023-09-03 10:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Discount name')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priority')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='Sale value')),
                ('data_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount start')),
                ('data_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount end')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Amount of products for a success discount')),
                ('quantity', models.PositiveIntegerField(default=2, verbose_name='Quantity of products for a success discount')),
            ],
            options={
                'verbose_name': 'Cart discount',
                'verbose_name_plural': 'Cart discounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.FileField(upload_to='images/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('title', models.CharField(max_length=255, verbose_name='Title  ')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('is_limited', models.BooleanField(default=True, verbose_name='Limited')),
                ('is_delivery', models.BooleanField(default=True, verbose_name='Delivery')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='Category')),
                ('image', models.ManyToManyField(related_name='image_to_product', to='catalog_app.image', verbose_name='Image')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Discount name')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priority')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='Sale value')),
                ('data_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount start')),
                ('data_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount end')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Group of product discount',
                'verbose_name_plural': 'Group of product discounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Discount name')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priority')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='Sale value')),
                ('data_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount start')),
                ('data_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount end')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product discount',
                'verbose_name_plural': 'Product discounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('image', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='Image')),
                ('category_min_price', models.PositiveIntegerField(default=1, verbose_name='Minimal price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
                'ordering': ['id'],
            },
        ),
    ]
