# Generated by Django 4.2 on 2023-09-14 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicproduct',
            name='characteristic_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog_app.characteristicvalue', verbose_name='value of characteristic'),
        ),
        migrations.AlterField(
            model_name='characteristicproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='catalog_app.product', verbose_name='product'),
        ),
    ]
