# Generated by Django 4.2 on 2023-09-14 07:00

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['id'], 'verbose_name': 'banner', 'verbose_name_plural': 'banners'},
        ),
        migrations.AlterModelOptions(
            name='cartsale',
            options={'ordering': ['id'], 'verbose_name': 'cart discount', 'verbose_name_plural': 'cart discounts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='discountproduct',
            options={'ordering': ['id'], 'verbose_name': 'product discount', 'verbose_name_plural': 'product discounts'},
        ),
        migrations.AlterModelOptions(
            name='discountproductgroup',
            options={'ordering': ['id'], 'verbose_name': 'group of product discount', 'verbose_name_plural': 'group of product discounts'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['id'], 'verbose_name': 'image', 'verbose_name_plural': 'images'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id'], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'ordering': ['id'], 'verbose_name': 'slider', 'verbose_name_plural': 'sliders'},
        ),
        migrations.AddField(
            model_name='cartsale',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='discountproduct',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AddField(
            model_name='discountproductgroup',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='category_min_price',
            field=models.PositiveIntegerField(default=1, verbose_name='minimal price'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=7, verbose_name='amount of products for a success discount'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='data_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of discount end'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='data_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of discount start'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='name',
            field=models.CharField(max_length=255, verbose_name='discount name'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='quantity',
            field=models.PositiveIntegerField(default=2, verbose_name='quantity of products for a success discount'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='cartsale',
            name='value',
            field=models.PositiveIntegerField(default=1, verbose_name='sale value'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(upload_to='images/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='data_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of discount end'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='data_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of discount start'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='name',
            field=models.CharField(max_length=255, verbose_name='discount name'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='discountproduct',
            name='value',
            field=models.PositiveIntegerField(default=1, verbose_name='sale value'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='data_end',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of discount end'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='data_start',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date of discount start'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='discount name'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='priority',
            field=models.PositiveIntegerField(default=1, verbose_name='priority'),
        ),
        migrations.RemoveField(
            model_name='discountproductgroup',
            name='product',
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='discountproductgroup',
            name='value',
            field=models.PositiveIntegerField(default=1, verbose_name='sale value'),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ManyToManyField(related_name='image_to_product', to='catalog_app.image', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_delivery',
            field=models.BooleanField(default=True, verbose_name='delivery'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_limited',
            field=models.BooleanField(default=True, verbose_name='limited'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title  '),
        ),
        migrations.AlterField(
            model_name='product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='creation time'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(blank=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated time'),
        ),
        migrations.CreateModel(
            name='Rewiew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('text', models.CharField(max_length=255, verbose_name='text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='rewiew')),
            ],
            options={
                'verbose_name': 'rewiew',
                'verbose_name_plural': 'reviews',
            },
        ),
        migrations.AddField(
            model_name='discountproductgroup',
            name='product',
            field=models.ManyToManyField(to='catalog_app.product', verbose_name='product'),
        ),
    ]
