# Generated by Django 4.2 on 2023-08-30 09:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0002_slider_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Discount name')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priority')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='Sale value')),
                ('data_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount start')),
                ('data_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount end')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=7, verbose_name='Amount of products for a success discount')),
                ('quantity', models.PositiveIntegerField(default=2, verbose_name='Quantity of products for a success discount')),
            ],
            options={
                'verbose_name': 'Cart discount',
                'verbose_name_plural': 'Cart discounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountProductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Discount name')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priority')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='Sale value')),
                ('data_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount start')),
                ('data_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount end')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Group of product discount',
                'verbose_name_plural': 'Group of product discounts',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DiscountProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=255, verbose_name='Discount name')),
                ('priority', models.PositiveIntegerField(default=1, verbose_name='Priority')),
                ('value', models.PositiveIntegerField(default=1, verbose_name='Sale value')),
                ('data_start', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount start')),
                ('data_end', models.DateField(default=django.utils.timezone.now, verbose_name='Date of discount end')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='Category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.product', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Product discount',
                'verbose_name_plural': 'Product discounts',
                'ordering': ['id'],
            },
        ),
    ]
