# Generated by Django 4.2 on 2023-09-12 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0002_characteristictype_rewiew_chatacteristicvalue_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChatacteristicProduct',
            new_name='CharacteristicProduct',
        ),
        migrations.RenameModel(
            old_name='ChatacteristicValue',
            new_name='CharacteristicValue',
        ),
        migrations.AlterModelOptions(
            name='characteristictype',
            options={'verbose_name': 'type characteristic of product', 'verbose_name_plural': 'types characteristic of product'},
        ),
        migrations.AlterModelOptions(
            name='characteristicvalue',
            options={'verbose_name': 'characteristic of product', 'verbose_name_plural': 'characteristic of product'},
        ),
    ]
