# Generated by Django 4.2 on 2023-09-28 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_productviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='category_min_price',
        ),
    ]
