# Generated by Django 4.2 on 2023-10-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_alter_rewiew_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='number_of_sales',
            field=models.IntegerField(blank=True, default=0, verbose_name='number_of_sales'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=255, verbose_name='title'),
        ),
    ]
