# Generated by Django 4.2 on 2023-08-25 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0003_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
