# Generated by Django 4.2 on 2023-10-09 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0004_remove_banner_category_min_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewiew',
            options={'ordering': ['created_at'], 'verbose_name': 'rewiew', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterField(
            model_name='rewiew',
            name='text',
            field=models.TextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='rewiew',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='author'),
        ),
    ]
