# Generated by Django 4.2 on 2023-09-12 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0004_alter_characteristicproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characteristicproduct',
            options={'verbose_name': 'characteristic of product', 'verbose_name_plural': 'characteristics of product'},
        ),
        migrations.AlterModelOptions(
            name='characteristicvalue',
            options={'verbose_name': 'characteristic value', 'verbose_name_plural': 'characteristic values'},
        ),
        migrations.AlterField(
            model_name='characteristictype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characterisic_type', to='catalog_app.category', verbose_name='category'),
        ),
    ]
