# Generated by Django 4.2 on 2023-10-22 01:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_app', '0004_product_number_of_sales_alter_product_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['svg'])], verbose_name='image'),
        ),
    ]
