# Generated by Django 4.2 on 2023-09-12 13:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog_app', '0006_alter_characteristicproduct_characteristic_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characteristicproduct',
            name='characteristic_value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_product', to='catalog_app.characteristicvalue', verbose_name='value of characteristic'),
        ),
        migrations.AlterField(
            model_name='characteristicproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_product', to='catalog_app.product', verbose_name='product'),
        ),
        migrations.AlterField(
            model_name='characteristictype',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog_app.category', verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='characteristicvalue',
            name='characteristic_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_value', to='catalog_app.characteristictype', verbose_name='type of characteristic'),
        ),

    ]
