# Generated by Django 4.2 on 2023-08-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_user_activation_key_expires_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
