# Generated by Django 4.2 on 2023-08-30 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_activation_key_expired',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
